version: '3'


volumes:
  nexus-data-volume:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: ./nexus-data
  jenkins-data-volume:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: ./jenkins-data
  gitlab-config-volume:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: ./gitlab-config
  gitlab-data-volume:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: ./gitlab-data
  
services:
  gitlab:
    image: "gitlab/gitlab-ce:13.7.3-ce.0"
    stdin_open: true
    tty: true        
    restart: always
    networks:
      - virtualnetwork
    ports:
      - "8080:80"
    volumes:
      - gitlab-config-volume:/etc/gitlab
      - gitlab-data-volume:/var/opt/gitlab
  jenkins:
    image: "jenkins:2.60.3-alpine"
    stdin_open: true
    tty: true        
    restart: always
    ports:
      - "8081:8080"
    networks:
      - virtualnetwork
    volumes:
      - jenkins-data-volume:/var/jenkins_home
  nexus:
    image: "sonatype/nexus3:3.29.2"
    stdin_open: true
    tty: true        
    restart: always
    ports:
      - "8082:8081"
      - "8282:8282" # Port for docker for docker repository group (dockerhub proxy + docker-snapshots + docker-releases)
    networks:
      - virtualnetwork
    volumes:
      - nexus-data-volume:/nexus-data

networks:
  virtualnetwork:
    driver: overlay
    ipam:
      config:
        - subnet: 192.168.168.0/24